language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
before_install:
    sudo apt-get install -y python-gevent python-lxml
install: 
    pip install -r requirements-travis.txt --use-mirrors
# command to run tests
script: make ci_test

