language: python
python:
  - "2.6"
  - "2.7"

install:
    # update aptitude
    - sudo apt-get update -y

    # install aptitude packages
    - LDFLAGS=-lm sudo apt-get install -y $(< requirements-travis.txt)

    # install python requirements
    - pip install -r test_requirements.txt --use-mirrors
    - pip install coveralls

    # weird travis-ci python paths
    - export PYTHONPATH=$PYTHONPATH:/usr/lib/pymodules/python2.7/
    - export PYTHONPATH=$PYTHONPATH:/usr/lib/python2.7/dist-packages
    - export PYTHONPATH=$PYTHONPATH:/usr/lib/pyshared/python2.7/
    - export PYTHONPATH=$PYTHONPATH:/usr/local/lib/python2.7/site-packages/

    # verify requirements were met
    - INSTALLDIR=$(python -c "import os; import gevent; print(os.path.dirname(gevent.__file__))")


script:
    - export PYTHONPATH=$PYTHONPATH:/usr/lib/pymodules/python2.7/
    - export PYTHONPATH=$PYTHONPATH:/usr/lib/python2.7/dist-packages
    - export PYTHONPATH=$PYTHONPATH:/usr/lib/pyshared/python2.7/
    - export PYTHONPATH=$PYTHONPATH:/usr/local/lib/python2.7/site-packages/

    # finally run tests
    - coverage run --source=pyvows make ci_test


after_success:
    - coveralls
